version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "1004:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ocholi
      WORDPRESS_DB_PASSWORD: 1215Jack_01
      WORDPRESS_DB_NAME: ocholi_db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ocholi_db
      MYSQL_USER: ocholi
      MYSQL_PASSWORD: 1215Jack_01
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1044:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 10_kcaJ5121
    networks:
      - wp_network

volumes:
  wordpress_data:
  db_data:

networks:
  wp_network:
